name: Build Minecraft Forge Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 JDK 8
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8

    # 3. 缓存 Gradle
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-

    # 4. 构建 Forge Mod
    - name: Build mod
      run: ./gradlew build --no-daemon --refresh-dependencies

    # 5. 上传构建产物
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: mod-jar
        path: build/libs/*.jar
