name: Build Minecraft Forge Mod (JRE 8 Compatible)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 JDK 11（构建用）
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    # 3. 缓存 Gradle 依赖
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
        restore-keys: |
          gradle-

    # 4. 安装系统 Gradle（如果没有 wrapper）
    - name: Install Gradle
      run: sudo apt-get update && sudo apt-get install -y gradle

    # 5. 构建 Forge Mod
    - name: Build mod
      run: gradle build --no-daemon --refresh-dependencies

    # 6. 上传构建产物
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: mod-jar
        path: build/libs/*.jar
